# -*- coding: utf-8 -*-
"""Untitled14(TSA_1136_final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126M5MrjCTCvg1gKhDqgE8XqzdR_cmFtX
"""

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Battery_dataset.csv")
df.head()

df.columns

!nvidia-smi

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

df = pd.read_csv("/content/drive/MyDrive/Battery_dataset.csv")
print(df.shape)
df.head()

df.info()
df.isna().sum()

df = df.dropna()  # or fill with df.fillna(method='ffill')

scaler = MinMaxScaler()
feature_cols = ['chI', 'chV', 'chT', 'disI', 'disV', 'disT', 'BCt']
df[feature_cols] = scaler.fit_transform(df[feature_cols])

df = df.sort_values(by=['battery_id', 'cycle'])

def create_sequences(data, seq_length, target_col):
    xs, ys = [], []
    for i in range(len(data) - seq_length):
        x = data.iloc[i:(i+seq_length)][feature_cols].values
        y = data.iloc[i+seq_length][target_col]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

SEQ_LEN = 20
X, y = create_sequences(df, SEQ_LEN, 'SOH')
X.shape, y.shape

model_soh = Sequential([
    LSTM(64, return_sequences=True, input_shape=(SEQ_LEN, len(feature_cols))),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(1)
])

model_soh.compile(optimizer='adam', loss='mse', metrics=['mae'])
model_soh.summary()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history_soh = model_soh.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

plt.plot(history_soh.history['loss'], label='train')
plt.plot(history_soh.history['val_loss'], label='val')
plt.legend()
plt.title('SOH Model Loss')
plt.show()

soh_preds = model_soh.predict(X_test)
plt.scatter(y_test, soh_preds, alpha=0.6)
plt.xlabel('True SOH')
plt.ylabel('Predicted SOH')
plt.title('SOH Prediction Performance')
plt.show()

from sklearn.metrics import r2_score

y_pred = model_soh.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.4f}")

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

# Predictions
y_pred = model_soh.predict(X_test)

# Metrics
r2  = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)

# Print results
print(f"R² Score: {r2:.4f}")
print(f"MSE     : {mse:.4f}")
print(f"MAE     : {mae:.4f}")
print(f"MAPE    : {mape:.4f}")

model_soh = Sequential([
    LSTM(128, return_sequences=True, input_shape=(SEQ_LEN, len(feature_cols))),
    Dropout(0.2),
    LSTM(64, return_sequences=True),
    Dropout(0.2),
    LSTM(32),
    Dense(16, activation='relu'),
    Dense(1)
])
model_soh.compile(optimizer='adam', loss='mse', metrics=['mae'])

reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=0.0001)

history = model_soh.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[reduce_lr, EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)],
    verbose=1
)

from sklearn.metrics import r2_score

y_pred = model_soh.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.4f}")

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

# Predictions
y_pred = model_soh.predict(X_test)

# Metrics
r2  = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)

# Print results
print(f"R² Score: {r2:.4f}")
print(f"MSE     : {mse:.4f}")
print(f"MAE     : {mae:.4f}")
print(f"MAPE    : {mape:.4f}")

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train.reshape(-1, X_train.shape[-1])).reshape(X_train.shape)
X_test_scaled = scaler.transform(X_test.reshape(-1, X_test.shape[-1])).reshape(X_test.shape)

df['deltaV'] = df['chV'] - df['disV']
df['deltaI'] = df['chI'] - df['disI']
df['deltaT'] = df['chT'] - df['disT']
feature_cols += ['deltaV', 'deltaI', 'deltaT']

def create_sequences(data, target, seq_len):
    X, y = [], []
    for i in range(len(data)-seq_len):
        X.append(data[i:i+seq_len])
        y.append(target[i+seq_len])
    return np.array(X), np.array(y)

from tensorflow.keras.layers import Bidirectional

model = Sequential([
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(SEQ_LEN, len(feature_cols))),
    Dropout(0.2),
    Bidirectional(LSTM(64)),
    Dense(32, activation='relu'),
    Dense(1)
])

from tensorflow.keras.layers import BatchNormalization

model.add(BatchNormalization())

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-5)

from tensorflow.keras.optimizers import Adam

# Optimizer
optimizer = Adam(learning_rate=0.001)  # default learning rate is good for LSTM

# Compile model with optimizer
model_soh.compile(optimizer=optimizer, loss='mse', metrics=['mae'])

# Training parameters
EPOCHS = 100         # Number of epochs (use EarlyStopping to avoid overfitting)
BATCH_SIZE = 32      # Batch size suitable for LSTM

history = model_soh.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model_soh.predict(X_test)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"R² Score: {r2:.4f}")
print(f"MAE: {mae:.4f}")

model_soh.save("/content/drive/MyDrive/model_soh.h5")
print("Model saved to Google Drive.")

from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error
)
import numpy as np

# Predictions
y_pred = model_soh.predict(X_test)

# Metrics
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)

# Print results
print(f"R² Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"MAPE     : {mape:.4f}  ({mape*100:.2f}%)")

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6, label='Predicted vs Actual')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction')
plt.xlabel("Actual SOH")
plt.ylabel("Predicted SOH")
plt.title(f"Actual vs Predicted SOH\nR² = {r2:.4f}, MAE = {mae:.2f}")
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Flatten predictions if needed
y_pred_flat = y_pred.flatten()

plt.figure(figsize=(12,6))
plt.plot(y_test, label='True SOH', color='blue')
plt.plot(y_pred_flat, label='Predicted SOH', color='red', linestyle='--')
plt.title('Battery SOH Prediction')
plt.xlabel('Test Sample')
plt.ylabel('SOH')
plt.legend()
plt.grid(True)
plt.show()

y_pred_flat = y_pred.flatten()
residuals = y_test - y_pred_flat

plt.figure(figsize=(8,6))
plt.scatter(y_pred_flat, residuals, color='green', alpha=0.6)
plt.axhline(y=0, color='r', linestyle='--', lw=2)
plt.xlabel("Predicted SOH")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.grid(True)
plt.show()



target_col = 'RUL'
feature_cols = ['chI','chV','chT','disI','disV','disT','BCt','deltaV','deltaI','deltaT']  # include engineered features

# Example: define EOL as SOH <= 70
df['RUL'] = df.groupby('battery_id')['cycle'].transform('max') - df['cycle']

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[feature_cols] = scaler.fit_transform(df[feature_cols])

SEQ_LEN = 20  # can tune 10-30
def create_sequences(data, seq_length, target_col):
    xs, ys = [], []
    for i in range(len(data) - seq_length):
        x = data.iloc[i:(i+seq_length)][feature_cols].values
        y = data.iloc[i+seq_length][target_col]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

X, y = create_sequences(df, SEQ_LEN, 'RUL')

split_idx = int(0.8 * len(X))
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional, BatchNormalization
from tensorflow.keras.optimizers import Adam

model_rul = Sequential([
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(SEQ_LEN, len(feature_cols))),
    BatchNormalization(),
    Dropout(0.2),
    Bidirectional(LSTM(64)),
    BatchNormalization(),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1)
])

optimizer = Adam(learning_rate=0.001)
model_rul.compile(optimizer=optimizer, loss='mse', metrics=['mae'])

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-5)

history = model_rul.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

y_pred = model_rul.predict(X_test).flatten()

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"R² Score: {r2:.4f}")

print(f"MAE: {mae:.4f}")

from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error
)
import numpy as np

# Predictions (flatten if needed)
y_pred = model_rul.predict(X_test).flatten()

# Metrics
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)

# Print all metrics
print(f"R² Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"MAPE     : {mape:.4f} ({mape*100:.2f}%)")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout, Bidirectional, BatchNormalization
from tensorflow.keras.optimizers import Adam

model_rul = Sequential([
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(SEQ_LEN, len(feature_cols))),
    BatchNormalization(),
    Dropout(0.2),

    Bidirectional(GRU(64, return_sequences=False)),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1)  # RUL output
])

optimizer = Adam(learning_rate=0.001)
model_rul.compile(optimizer=optimizer, loss='mse', metrics=['mae'])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout, Bidirectional, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Hyperparameters
SEQ_LEN = 30  # sequence length, can tune 20-50
num_features = X_train.shape[2]  # number of features
learning_rate = 0.001
batch_size = 32
epochs = 100

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=7, min_lr=1e-5)

# Model
model_rul = Sequential([
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(SEQ_LEN, num_features)),
    BatchNormalization(),
    Dropout(0.2),

    Bidirectional(GRU(64, return_sequences=False)),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1)  # RUL output
])

optimizer = Adam(learning_rate=learning_rate)
model_rul.compile(optimizer=optimizer, loss='mse', metrics=['mae'])
model_rul.summary()

history = model_rul.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=epochs,
    batch_size=batch_size,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

y_pred = model_rul.predict(X_test).flatten()

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"R² Score: {r2:.4f}")
print(f"MAE: {mae:.4f}")

from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error
)
import numpy as np

# Predictions (flatten if needed)
y_pred = model_rul.predict(X_test).flatten()

# Metrics
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)

# Print all metrics
print(f"R² Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"MAPE     : {mape:.4f} ({mape*100:.2f}%)")

# Absolute MAE you already have
from sklearn.metrics import mean_absolute_error

y_pred = model_rul.predict(X_test).flatten()
mae = mean_absolute_error(y_test, y_pred)

# Option 1: Relative MAE based on max RUL
relative_mae_max = (mae / y_test.max()) * 100

# Option 2: Relative MAE based on mean RUL
relative_mae_mean = (mae / y_test.mean()) * 100

print(f"Absolute MAE: {mae:.2f} cycles")
print(f"Relative MAE vs Max RUL: {relative_mae_max:.2f}%")
print(f"Relative MAE vs Mean RUL: {relative_mae_mean:.2f}%")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout, Bidirectional, BatchNormalization
from tensorflow.keras.optimizers import Adam

# Assume:
# X_train.shape[2] = number of features (including SOH_pred and delta features)
num_features = X_train.shape[2]
SEQ_LEN = 40  # increased sequence length to capture longer trends

model_rul = Sequential([
    # First Bidirectional LSTM layer
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(SEQ_LEN, num_features)),
    BatchNormalization(),
    Dropout(0.2),

    # Second Bidirectional GRU layer
    Bidirectional(GRU(64, return_sequences=False)),
    BatchNormalization(),
    Dropout(0.2),

    # Fully connected layers
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1)  # RUL output
])

# Compile model with lower learning rate for finer training
optimizer = Adam(learning_rate=0.0005)
model_rul.compile(optimizer=optimizer, loss='mse', metrics=['mae'])
model_rul.summary()

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Hyperparameters
epochs = 120            # Can adjust 100–150 depending on convergence
batch_size = 32         # Typical for time-series
learning_rate = 0.0005  # Already set in model compilation

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=7, min_lr=1e-6)

# Fit the model
history = model_rul.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=epochs,
    batch_size=batch_size,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

# Predict on test set
y_pred = model_rul.predict(X_test).flatten()

# Metrics
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"R² Score: {r2:.4f}")
print(f"MAE: {mae:.4f}")

from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

# Predict on test set
y_pred = model_rul.predict(X_test).flatten()

# Metrics
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"R² Score: {r2:.4f}")
print(f"MAE: {mae:.4f}")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout, Bidirectional, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber

# ------------------------------
# Model Parameters
# ------------------------------
num_features = X_train.shape[2]
SEQ_LEN = 25

# ------------------------------
# Build Sequential Model
# ------------------------------
model_rul = Sequential([
    # First Bidirectional LSTM layer
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(SEQ_LEN, num_features)),
    BatchNormalization(),
    Dropout(0.3),  # slightly higher dropout

    # Second Bidirectional GRU layer
    Bidirectional(GRU(64, return_sequences=False)),
    BatchNormalization(),
    Dropout(0.3),

    # Fully connected layers with L2 regularization
    Dense(32, activation='relu', kernel_regularizer=l2(0.001)),
    Dropout(0.2),
    Dense(1)  # RUL output
])

# ------------------------------
# Compile Model
# ------------------------------
optimizer = Adam(learning_rate=0.0005)
model_rul.compile(optimizer=optimizer, loss=Huber(), metrics=['mae'])
model_rul.summary()

# ------------------------------
# Callbacks for training
# ------------------------------
early_stop = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6)

# ------------------------------
# Train Model
# ------------------------------
history = model_rul.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=64,
    callbacks=[early_stop, reduce_lr]
)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
import numpy as np

# Predict on test set
y_pred = model_rul.predict(X_test).flatten()  # flatten in case output shape is (n,1)

# Metrics
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)

# Print all metrics
print(f"R² Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print(f"MAE      : {mae:.4f}")
#print(f"MAPE     : {mape:.4f} ({mape*100:.2f}%)")

nrmse = rmse / (y_test.max() - y_test.min())
print(f"NRMSE (normalized): {nrmse:.4f}")

import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# ------------------------------
# Predict
# ------------------------------
y_pred = model_rul.predict(X_test).flatten()

# ------------------------------
# Compute Metrics
# ------------------------------
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
nrmse = rmse / (y_test.max() - y_test.min())  # normalized RMSE

print(f"R² Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"NRMSE    : {nrmse:.4f}")

# ------------------------------
# Actual vs Predicted Plot
# ------------------------------
plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.6, color='blue')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel("Actual RUL")
plt.ylabel("Predicted RUL")
plt.title("Actual vs Predicted RUL")
plt.grid(True)
plt.show()

# ------------------------------
# Residual Plot
# ------------------------------
residuals = y_test - y_pred
plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals, alpha=0.6, color='green')
plt.hlines(y=0, xmin=y_pred.min(), xmax=y_pred.max(), colors='r', linestyles='dashed')
plt.xlabel("Predicted RUL")
plt.ylabel("Residuals (Actual - Predicted)")
plt.title("Residual Plot")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# Predict
y_pred = model_rul.predict(X_test).flatten()

# Metrics
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
nrmse = rmse / (y_test.max() - y_test.min())

print(f"R² Score : {r2:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"NRMSE    : {nrmse:.4f}")

# ------------------------------
# Actual vs Predicted Plot with Legend
# ------------------------------
plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.6, color='blue', label='Predicted vs Actual')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction')
plt.xlabel("Actual RUL")
plt.ylabel("Predicted RUL")
plt.title("Actual vs Predicted RUL")
plt.legend()
plt.grid(True)
plt.show()

# ------------------------------
# Residual Plot with Legend
# ------------------------------
residuals = y_test - y_pred
plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals, alpha=0.6, color='green', label='Residuals')
plt.hlines(y=0, xmin=y_pred.min(), xmax=y_pred.max(), colors='r', linestyles='dashed', label='Zero Error Line')
plt.xlabel("Predicted RUL")
plt.ylabel("Residuals (Actual - Predicted)")
plt.title("Residuals vs Predicted RUL")
plt.legend()
plt.grid(True)
plt.show()

